### ISSUE TITLE
data input

### ISSUE THREAD

**Issue by diego1109** [ringringyi/DOTA_models#1]
hi, I don't know how to organize dota dataset,when I convert it to TFRecords.Can you privde more details under data-dir.
thanks very much!

**Comment by emo-farmer** [comment]
> hi, I don't know how to organize dota dataset,when I convert it to TFRecords.Can you privde more details under data-dir.
> thanks very much!

How do you convert the raw data to TFRecords? I can't find the index files named "test.txt" and "train.txt", which are need in "create_dota_tf_record.py".

Many thanks

**Comment by shivi0011** [comment]
you need to generate these files... train.txt will contain all the files with path with extension needed for training. and similarly for test.txt using the DOTA dataset.

**Comment by xdd0109** [comment]
/home/xjd/anaconda2/lib/python2.7/site-packages/h5py/init.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
from ._conv import register_converters as _register_converters
('Called with argument:', Namespace(cfg='experiments/faster_rcnn/cfgs/DOTA_quadrangle.yaml', frequent=100))
{'CLASS_AGNOSTIC': False,
'MXNET_VERSION': 'mxnet',
'RESIZE_TO_FIX_SIZE': True,
'SCALES': [(1024, 1024)],
'TEST': {'BATCH_IMAGES': 1,
'CXX_PROPOSAL': False,
'DO_MULTISCALE_TEST': False,
'HAS_RPN': True,
'MULTISCALE': [1.0, 1.2, 1.4, 1.6],
'NMS': 0.3,
'PROPOSAL_MIN_SIZE': 0,
'PROPOSAL_NMS_THRESH': 0.7,
'PROPOSAL_POST_NMS_TOP_N': 2000,
'PROPOSAL_PRE_NMS_TOP_N': 20000,
'RPN_MIN_SIZE': 0,
'RPN_NMS_THRESH': 0.7,
'RPN_POST_NMS_TOP_N': 300,
'RPN_PRE_NMS_TOP_N': 6000,
'max_per_image': 300,
'save_img_path': '/home/dj/data/vis',
'test_epoch': 59},
'TRAIN': {'ALTERNATE': {'RCNN_BATCH_IMAGES': 0,
'RPN_BATCH_IMAGES': 0,
'rfcn1_epoch': 0,
'rfcn1_lr': 0,
'rfcn1_lr_step': '',
'rfcn2_epoch': 0,
'rfcn2_lr': 0,
'rfcn2_lr_step': '',
'rpn1_epoch': 0,
'rpn1_lr': 0,
'rpn1_lr_step': '',
'rpn2_epoch': 0,
'rpn2_lr': 0,
'rpn2_lr_step': '',
'rpn3_epoch': 0,
'rpn3_lr': 0,
'rpn3_lr_step': ''},
'ASPECT_GROUPING': True,
'BATCH_IMAGES': 1,
'BATCH_ROIS': 128,
'BATCH_ROIS_OHEM': 128,
'BBOX_MEANS': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
'BBOX_NORMALIZATION_PRECOMPUTED': False,
'BBOX_REGRESSION_THRESH': 0.5,
'BBOX_STDS': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
'BBOX_WEIGHTS': array([1., 1., 1., 1., 1., 1., 1., 1.]),
'BG_THRESH_HI': 0.5,
'BG_THRESH_LO': 0.1,
'CXX_PROPOSAL': False,
'ENABLE_OHEM': True,
'END2END': True,
'FG_FRACTION': 0.25,
'FG_THRESH': 0.5,
'FLIP': True,
'RESUME': False,
'RPN_BATCH_SIZE': 256,
'RPN_BBOX_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
'RPN_CLOBBER_POSITIVES': False,
'RPN_FG_FRACTION': 0.5,
'RPN_MIN_SIZE': 0,
'RPN_NEGATIVE_OVERLAP': 0.3,
'RPN_NMS_THRESH': 0.7,
'RPN_POSITIVE_OVERLAP': 0.7,
'RPN_POSITIVE_WEIGHT': -1.0,
'RPN_POST_NMS_TOP_N': 300,
'RPN_PRE_NMS_TOP_N': 6000,
'SHUFFLE': True,
'begin_epoch': 0,
'end_epoch': 60,
'lr': 0.0005,
'lr_factor': 0.1,
'lr_step': '45,52',
'model_prefix': 'rcnn_DOTA_quadrangle',
'momentum': 0.9,
'warmup': True,
'warmup_lr': 5e-05,
'warmup_step': 1000,
'wd': 0.0005},
'dataset': {'NUM_CLASSES': 16,
'dataset': 'DOTA_oriented',
'dataset_path': './path-to-dota-split',
'image_set': 'train',
'proposal': 'rpn',
'root_path': './result',
'test_image_set': 'test'},
'default': {'frequent': 100, 'kvstore': 'device'},
'gpus': '0',
'network': {'ANCHOR_RATIOS': [0.5, 1, 2],
'ANCHOR_SCALES': [8, 16, 32],
'FIXED_PARAMS': ['conv1',
'bn_conv1',
'res2',
'bn2',
'gamma',
'beta'],
'FIXED_PARAMS_SHARED': ['conv1',
'bn_conv1',
'res2',
'bn2',
'res3',
'bn3',
'res4',
'bn4',
'gamma',
'beta'],
'IMAGE_STRIDE': 0,
'NUM_ANCHORS': 9,
'PIXEL_MEANS': array([103.06, 115.9 , 123.15]),
'RCNN_FEAT_STRIDE': 16,
'RPN_FEAT_STRIDE': 16,
'pretrained': './model/pretrained_model/resnet_v1_101',
'pretrained_epoch': 0},
'output_path': './output/rcnn/DOTA_quadrangle',
'symbol': 'resnet_v1_101_rcnn_quadrangle'}
num_images 0
DOTA_oriented_train gt roidb loaded from ./result/cache/DOTA_oriented_train_gt_roidb.pkl
append flipped images to roidb
filtered 0 roidb entries: 0 -> 0
Traceback (most recent call last):
File "experiments/faster_rcnn/rcnn_dota_quadrangle_e2e.py", line 23, in 
train_quadrangle_end2end.main()
File "experiments/faster_rcnn/../../faster_rcnn/train_quadrangle_end2end.py", line 165, in main
config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
File "experiments/faster_rcnn/../../faster_rcnn/train_quadrangle_end2end.py", line 81, in train_net
anchor_ratios=config.network.ANCHOR_RATIOS, aspect_grouping=config.TRAIN.ASPECT_GROUPING)
File "experiments/faster_rcnn/../../faster_rcnn/core/loader.py", line 659, in init
self.get_batch_individual()
File "experiments/faster_rcnn/../../faster_rcnn/core/loader.py", line 807, in get_batch_individual
iroidb = [roidb[i] for i in range(islice.start, islice.stop)]
IndexError: list index out of range

I have download the dota v1.0 already, and try to run with the usage as you mentioned before,but I can't run successfully.And I think the mistake is caused by dataset processing. I can't understand the meaning of your description of the test.txt ande the train.txt. Are the two txt files used to store the name of the train of test picture, such as P000001?
I'm looking forward to hearing from you.
Thank you.

你好，我是照着DOTA那边论文的git连接操作他们的实验的，也是弄不清楚这个train.txt和test.txt的意思，就是存放P0001着这样的图片名吗？

**Comment by lxyICT** [comment]
你好,请问索引文件 train.txt 里面 存放着的图片路径是否有什么含义,比如:
/your/path/to/dota/train/images/P2033__1__0___0.png
P2033是图片的名字, 请问里面的_1和_0是什么意思呢?
谢谢你啦~

**Comment by ZGX010** [comment]
不维护就关了了吧！小朋友！

**Comment by ZGX010** [comment]
import os

fir_dir = 'images'
img_list = os.listdir(fir_dir)
img_dir = os.path.abspath('images')
print(os.path.abspath('images'))
print(img_list)

full_abs_path = os.path.join(img_dir,img_list[1])
print("full_abs_path",full_abs_path)

txt = open('D:/DOTA_models-master/DOTA_models-master/object_detection/data_dir/train/train.txt','w+')
for i in range(len(img_list)):
    full_abs_path = os.path.join(os.path.join(img_dir,img_list[i]))
    txt.write(full_abs_path)
    txt.write('\n')

txt.close()

**Comment by ZGX010** [comment]
`import os

fir_dir = 'images'
img_list = os.listdir(fir_dir)
img_dir = os.path.abspath('images')
print(os.path.abspath('images'))
print(img_list)

full_abs_path = os.path.join(img_dir,img_list[1])
print("full_abs_path",full_abs_path)

txt = open('D:/DOTA_models-master/DOTA_models-master/object_detection/data_dir/train/train.txt','w+')
for i in range(len(img_list)):
    full_abs_path = os.path.join(os.path.join(img_dir,img_list[i]))
    txt.write(full_abs_path)
    txt.write('\n')

txt.close()`

**Comment by ZGX010** [comment]
`import os

fir_dir = 'images'
img_list = os.listdir(fir_dir)
img_dir = os.path.abspath('images')
print(os.path.abspath('images'))
print(img_list)

full_abs_path = os.path.join(img_dir,img_list[1])
print("full_abs_path",full_abs_path)

txt = open('D:/DOTA_models-master/DOTA_models-master/object_detection/data_dir/train/train.txt','w+')
for i in range(len(img_list)):
    full_abs_path = os.path.join(os.path.join(img_dir,img_list[i]))
    txt.write(full_abs_path)
    txt.write('\n')

txt.close()`
